### ISSUE TITLE
Implement data extension service

### ISSUE THREAD

**Issue by drkane** [drkane/datasette-reconcile#7]
https://reconciliation-api.github.io/specs/latest/#data-extension-service

**Comment by JBPressac** [comment]
Hello,
This implementation would be much appreciated ;-) ! Data extension properties could be by default all columns of the table. The label of the columns could be retrieved from the metadata.json file https://docs.datasette.io/en/stable/metadata.html#specifying-the-label-column-for-a-table.

**Comment by frafra** [comment]
I would like to join the effort to add this feature.

@drkane would you consider a PR?

**Comment by drkane** [comment]
@frafra Yes, that would be fantastic, I haven't had a chance to look at it, but it would be great.

**Comment by drkane** [comment]
In the latest version of the reconciliation API spec the extension endpoint is always `/extend` (see [Overview of possible routes](https://reconciliation-api.github.io/specs/latest/#overview-of-possible-routes)) so would make sense to use that by default for future-proofing.

**Comment by frafra** [comment]
I began working on it, but I had to stop for the moment. I hope I can resume in the next weeks.

**Comment by nicokant** [comment]
Hi, I've been working on this issue for a couple of days and I have sort of a prototype implementation ready, is it ok if I open a PR?

**Comment by drkane** [comment]
Now implemented - thanks @nicokant and @JBPressac
